### ISSUE TITLE
Getting NullPointerException while deploying Neural network Model 

### ISSUE THREAD

**Issue by RamakrishnaAddanki** [jpmml/jpmml-hive#1]
Hi folks, 
I am using Neural Network model with jpmm-hive and i am getting error as NullPointerException null and i am unable to find more info on the same on google and i am attaching screenshot regarding that error.please help me out in resolving this..
![hiveissue](https://cloud.githubusercontent.com/assets/14921776/17844027/a93dee32-6852-11e6-89ab-8b9c3f2c374c.PNG)

**Comment by vruusmann** [comment]
This screenshot does not contain any useful/actionable information. You need to see Hive log file for a complete stack trace.

Anyway, what's the point of pasting exception stack traces as images?
